# Project information
site_name: Introdução à Gestão
# define TOC or order of website-
nav:
  - Introdução: index.md
  - Informação Financeira:
      - Informação Financeira: inf_financeira.md
      - Exercícios: exercicios_1.md
  - Cálculo Financeiro:
      - Cálculo Financeiro: cal_financeiro.md
      - Exercícios: exercicios_2.md

site_author: Luis Barqueira
site_url: https://tourmaline-klepon-15f45d.netlify.app/
edit_uri: 'tree/main/docs'
docs_dir: docs

site_description:
  Introdução à gestão, teoria e exercícios

# Repository
repo_name: lbarqueira/introducao-gestao-material-mkdocs
repo_url: https://github.com/lbarqueira/introducao-gestao-material-mkdocs

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top  
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lbarqueira
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/barqueira
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/luis-barqueira-7369092/
  analytics:
    provider: google
    property: G-B8GM3TBF6K


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search

copyright: |
  &copy; 2023 <a href="https://github.com/lbarqueira"  target="_blank" rel="noopener">Luis Barqueira</a>
